version: '3.3'
services:
  mysql-container:
    image: mysql:8
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: Simple@123
      MYSQL_DATABASE: capstonedb1
    ports:
      - 3307:3306
    restart: always

  eureka-server:
    build: ./backend/EurekaServer/
    ports:
      - 8761:8761
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  microservice1:
    build: ./backend/backend-micro-service-app/
    ports:
      - 9090:9090
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_APPLICATION_NAME=microservice1
    depends_on:
      - mysql-container
      - eureka-server
    restart: always

  angular-container:
    build: ./frontend/front-end-app/dist/
    container_name: angular-container
    ports:
      - 80:80
    restart: always 